# This is a basic workflow to help you get started with Actions

name: Retag

# Controls when the workflow will run
on:
  #  # Triggers the workflow on push or pull request events but only for the "main" branch
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]

  # Shedule 1 fois par semaine
  schedule:
    - cron: "0 18 * * 0"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  retag:
    uses: laveracloudsolutions/github-pipeline-library/.github/workflows/retag.yml@main
    with:
      source-image: ghcr.io/laveracloudsolutions/php-runner:8.4-apache-trixie
      version-cmd: php -r "echo PHP_VERSION;"
    secrets: inherit